use_default_settings:
  engines:
    keep_only:
      - duckduckgo
      - bing
      - mojeek
      - qwant
      - yahoo
      - mwmbl
      - wiby
      - wikipedia
server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "ultrasecretkey"
  limiter: false
  image_proxy: false
  method: "POST"
search:
  safe_search: 1
  autocomplete: ""
  formats:
    - html
    - json
outgoing:
  request_timeout: 8.0
  max_request_timeout: 15.0
engines:
  - name: bing
    disabled: false
  - name: mojeek
    disabled: false
  - name: qwant
    disabled: false
  - name: yahoo
    disabled: false
  - name: mwmbl
    disabled: false
  - name: wiby
    disabled: false
  - name: wikipedia
    display_type:
      - infobox
      - list
logging:
  level: WARNING
